local deftest = require "deftest.deftest"

local test_http = require "test.test_http"
local test_vmath = require "test.test_vmath"
local test_mock_fs = require "test.test_mock_fs"
local test_mock_time = require "test.test_mock_time"
local test_mock = require "test.test_mock"
local test_unload = require "test.test_unload"
local test_mock_gui = require "test.test_mock_gui"
local test_check = require "test.test_check"
local telescope_spec = require "test.telescope_spec"

local container = require "integration.integration_tests_container"

-- TODO - remove.
function test_integration_tests(self)
	local wait_test = wait_test("Wait", function() end, function()
		return function()
			assert(go.get_position(".") == vmath.vector3(0, 0, 0))
		end 
	end, 1)
	container.add_test("Waiting test", wait_test)
	container.add_test("Waiting test 2", wait_test)
	msg.post("/integration_test_manager#integration_test_manager", "start")
end

function init(self)
	test_integration_tests(self)
	-- TODO - call deftest.run only after all integration tests are complete.
	
	deftest.add(test_http)
	deftest.add(test_vmath)
	deftest.add(telescope_spec)
	deftest.add(test_mock_fs)
	deftest.add(test_mock_time)
	deftest.add(test_mock)
	deftest.add(test_unload)
	deftest.add(test_mock_gui)
	deftest.add(test_check)
	deftest.add(integration_test)
	--deftest.run({ coverage = { enabled = true }, pattern = nil })
end