local deftest = require "deftest.deftest"

local test_http = require "test.test_http"
local test_vmath = require "test.test_vmath"
local test_mock_fs = require "test.test_mock_fs"
local test_mock_time = require "test.test_mock_time"
local test_mock = require "test.test_mock"
local test_unload = require "test.test_unload"
local test_mock_gui = require "test.test_mock_gui"
local test_check = require "test.test_check"
local telescope_spec = require "test.telescope_spec"

local container = require "integration.integration_tests_container"

function init(self)
	msg.post("/integration_test_manager#integration_test_manager", "start")
	
	deftest.add(test_http)
	deftest.add(test_vmath)
	deftest.add(telescope_spec)
	deftest.add(test_mock_fs)
	deftest.add(test_mock_time)
	deftest.add(test_mock)
	deftest.add(test_unload)
	deftest.add(test_mock_gui)
	deftest.add(test_check)
	deftest.add(integration_test)
	deftest.run({ coverage = { enabled = true }, pattern = nil })
end