local container = require "integration.integration_tests_container"

function init(self)
	self.max_time = 1
	self.time_since_test_start = 0
	self.running = false
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function get_message(self, message)
	container.add_processed_test(self.test_name, container.tests[self.test_name].test.after(message))
	msg.post(self.integration_test_manager, "test_processed", {test_name = self.test_name})
end

function test_after_waiting(self)
	self.running = false
	container.add_processed_test(self.test_name, container.tests[self.test_name].test.after())
	msg.post(self.integration_test_manager, "test_processed", {test_name = self.test_name})
end

function test_too_long(self)
	container.add_processed_test(self.test_name,
		function()
			describe(self.test_name, function()
				test("Test " .. self.test_name .. " has exceeded the time limit", function()
					assert(false)
				end)
			end)
		end
	)
	self.running = false
	msg.post(self.integration_test_manager, "test_too_long", {test_name = self.test_name})
end

function update(self, dt)
	if self.running then
		self.time_since_test_start = self.time_since_test_start + dt
		if self.time_since_test_start > self.max_time then
			if self.type == "wait" then
				test_after_waiting(self)
			else
				test_too_long(self)
			end
		end
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("execute") then
		self.test_name = message.test_name
		self.integration_test_manager = sender
		self.type = container.tests[message.test_name].test.type
		self.max_time = container.tests[message.test_name].test.time
		self.running = true
		container.tests[message.test_name].test.before()
	elseif self.running then
		if self.type == "message" and sender == container.tests[self.test_name].test.sender
		and message_id == hash(container.tests[self.test_name].test.message_id) then
			get_message(self, message)
		end
	end
end

-- Example of the .after fragment for message testing.
--	test.after = function(message)
--		return function()
-- 			describe("testing object", function()
--				test("testing object test", function()
--					assert(message.text == "Hello world!")
--				end)
--			end)
--		end
--	end

function on_input(self, action_id, action)
	-- Add input-handling code here. The game object this script is attached to
	-- must have acquired input focus:
	--
	--    msg.post(".", "acquire_input_focus")
	--
	-- All mapped input bindings will be received. Mouse and touch input will
	-- be received regardless of where on the screen it happened.
	-- Learn more: https://defold.com/manuals/input/
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
